# Generated by Django 3.2.3 on 2021-06-04 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210604_0624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Ostan',
            new_name='ostan',
        ),
    ]
