# Generated by Django 3.2.3 on 2021-06-04 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
        ('account', '0003_rename_ostan_user_ostan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bakhsh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='area.bakhsh', verbose_name='بخش'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dehestan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='area.dehestan', verbose_name='دهستان'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ostan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='area.ostan', verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='user',
            name='shahrestan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='area.shahrestan', verbose_name='شهرستان'),
        ),
    ]
