# Generated by Django 3.2.3 on 2021-06-04 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bakhsh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(auto_created=True, unique=True, verbose_name='موقعیت')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام استان')),
                ('active', models.BooleanField(default=True, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'بخش',
                'verbose_name_plural': 'بخش ها',
                'db_table': 'bakhsh_item',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Ostan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(auto_created=True, unique=True, verbose_name='موقعیت')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام استان')),
                ('active', models.BooleanField(default=True, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'استان ',
                'verbose_name_plural': 'استان ها',
                'db_table': 'ostan_item',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Shahrestan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(auto_created=True, unique=True, verbose_name='موقعیت')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام استان')),
                ('active', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('ostan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='area.ostan', verbose_name='استان')),
            ],
            options={
                'verbose_name': 'شهرستان',
                'verbose_name_plural': 'شهرستان ها',
                'db_table': 'shahrestan_item',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Dehestan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(auto_created=True, unique=True, verbose_name='موقعیت')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام استان')),
                ('active', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('bakhsh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='area.bakhsh', verbose_name='بخش')),
            ],
            options={
                'verbose_name': 'دهستان',
                'verbose_name_plural': 'دهستان ها',
                'db_table': 'dehestan_item',
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='bakhsh',
            name='shahrestan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='area.shahrestan', verbose_name='شهرستان'),
        ),
    ]
